FROM node:latest

WORKDIR /app

EXPOSE 8080

RUN npm init -y
RUN npm install express body-parser mysql nodemon cors express-session

# CMD ["node", "server.js"]

#CMD ["npx", "nodemon", "server.js"]

